### ISSUE TITLE
dep bonus and energy ?

### ISSUE THREAD

**Issue by emreb78** [joostsijm/rival_regions_calc#1]
thats nice work but i dont understand some thing. so i cant calculate true wage.
what is dep bonus?  i ask dep bonus becasuse my undestanding dep bonus is state resource bonus but there The value is displayed as a percentage and it can be max %10. But your test dep bonus value is 19. so i cant understand.   and why energy=1.9 in test_work_production.py.

**Comment by joostsijm** [comment]
Calculate wage is quite hard because of all the different variables. You're right about department bonus, it should be 10 max. I don't know know exactly why I used 1.9 energy but is should be 10. The test example is updated.
